# Generated by Django 3.2.5 on 2021-08-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_about',
        ),
    ]
