# Generated by Django 3.2.5 on 2021-08-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
